name: Android Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Install Python + Buildozer
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip zip unzip openjdk-17-jdk \
            libffi-dev libssl-dev autoconf automake libtool pkg-config zlib1g-dev
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install --user buildozer cython
          # Explicitly expose ~/.local/bin and link into global PATH
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          sudo ln -sf $HOME/.local/bin/buildozer /usr/local/bin/buildozer || true
          sudo chmod +x $HOME/.local/bin/buildozer || true
          buildozer version || true

      - name: Prepare Android SDK + NDK
        run: |
          mkdir -p /home/runner/android-sdk/cmdline-tools
          mkdir -p /home/runner/android-ndk
          cd /home/runner/android-sdk/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-9477386_latest.zip -O sdk.zip
          unzip -q sdk.zip && rm sdk.zip
          mv cmdline-tools latest
          yes | /home/runner/android-sdk/cmdline-tools/latest/bin/sdkmanager --sdk_root=/home/runner/android-sdk \
            "platform-tools" "build-tools;33.0.0" "platforms;android-33"
          cd /home/runner/android-ndk
          wget -q https://dl.google.com/android/repository/android-ndk-r25b-linux.zip -O ndk.zip
          unzip -q ndk.zip && rm ndk.zip
          mv android-ndk-r25b/* . && rm -rf android-ndk-r25b

      - name: Build APK
        env:
          ANDROID_HOME: /home/runner/android-sdk
          ANDROID_SDK_ROOT: /home/runner/android-sdk
          ANDROID_NDK_HOME: /home/runner/android-ndk
          PATH: /usr/local/bin:/home/runner/.local/bin:/home/runner/android-sdk/platform-tools:/home/runner/android-sdk/cmdline-tools/latest/bin:$PATH
        run: |
          which buildozer || (echo "❌ Buildozer not in PATH"; exit 1)
          buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: brahma_ai_vit_apk
          path: bin/*.apk
