name: Android Build
on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Java 17
        uses: actions/setup-java@v4
        with:
          distribution: zulu
          java-version: 17

      - name: Install dependencies
        run: |
          sudo apt-get update
          sudo apt-get install -y python3 python3-pip openjdk-17-jdk zip unzip \
              libffi-dev libssl-dev autoconf automake libtool pkg-config zlib1g-dev
          python3 -m pip install --upgrade pip setuptools wheel
          python3 -m pip install buildozer cython jinja2 appdirs colorama sh build toml packaging python-for-android
          echo "$HOME/.local/bin" >> $GITHUB_PATH
          which buildozer

      - name: Prepare Android SDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools
          cd $HOME/android-sdk/cmdline-tools
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O sdk.zip
          unzip -qo sdk.zip -d $HOME/android-sdk/cmdline-tools
          mv $HOME/android-sdk/cmdline-tools/cmdline-tools $HOME/android-sdk/cmdline-tools/latest
          export PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --sdk_root=$HOME/android-sdk --licenses || true
          sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "build-tools;33.0.0" "platforms;android-33" || true

      - name: Build APK
        run: buildozer android debug

      - name: Upload APK Artifact
        uses: actions/upload-artifact@v4
        with:
          name: apk
          path: bin/*.apk
