name: Android Build

on:
  push:
    branches: [ main ]
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Install Buildozer
        run: |
          sudo apt-get update -y
          sudo apt-get install -y unzip wget zlib1g-dev
          python3 -m pip install --upgrade pip setuptools wheel cython buildozer

      - name: Setup Android SDK + NDK
        run: |
          mkdir -p $HOME/android-sdk/cmdline-tools/latest
          cd $HOME/android-sdk/cmdline-tools/latest
          wget -q https://dl.google.com/android/repository/commandlinetools-linux-11076708_latest.zip -O sdk.zip
          unzip -qo sdk.zip && rm sdk.zip
          export PATH=$HOME/android-sdk/cmdline-tools/latest/bin:$PATH
          yes | sdkmanager --sdk_root=$HOME/android-sdk --licenses || true
          sdkmanager --sdk_root=$HOME/android-sdk "platform-tools" "platforms;android-33" "build-tools;33.0.2" "ndk;25.2.9519653"

      - name: Build APK
        run: |
          buildozer android debug

      - uses: actions/upload-artifact@v4
        with:
          name: GHOSH_Robotics_APK
          path: bin/*.apk
